---
driver:
  name: vagrant
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
# - name: ubuntu-10.04
# - name: centos-6.4
# - name: centos-5.9

suites:
- name: default
  run_list:
  - recipe[jenkins]
  attributes:
    jenkins:
      enable_proxy: false
- name: extra_config
  run_list:
  - recipe[jenkins]
  - recipe[jenkins_test::extra_config]
  attributes:
    jenkins:
      enable_proxy: false
- name: node
  run_list:
  - recipe[jenkins]
  - recipe[jenkins_test::node]
  attributes:
    jenkins:
      enable_proxy: false
      server:
        nodes:
          teapot:
            path: /home/jenkins
            labels:
            - iama
            - teapot
